version: "3.9"

services:
    # =================POSTGIS=SERVICE======================
    postgres:
        container_name: postgres
        env_file:
            - .env
        image: kartoza/postgis:14-3.1
        networks:
            - dms-network
        ports:
            - "5432:5432"
        restart: on-failure
        environment:
            - POSTGRES_DB=${DATABASE_NAME}
            - POSTGRES_USER=${DATABASE_USERNAME}
            - POSTGRES_PASS=${DATABASE_PASSWORD}
            - ALLOW_IP_RANGE=0.0.0.0/0
            - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting
        healthcheck:
            test: "exit 0"
        # healthcheck:
        #     test: [ "CMD-SHELL", "pg_isready -U postgres" ]
        #     interval: 5s
        #     timeout: 5s
        #     retries: 5
        volumes:
            - postgis-data:/var/lib/postgresql
            # - ./conf/l:/usr/local/bin/l
        #     - ./conf/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    # =================REDIS=CACHING=======================
    # redis:
    #     image: redis:6-alpine
    #     container_name: redis
    #     networks:
    #         - dms-network

    # =================DJANGO=SERVICE======================
    dms-backend:
        build:
            context: dms-backend
            dockerfile: Dockerfile
        container_name: backend
        depends_on:
            # redis:
            #   condition: service_started
            postgres:
                condition: service_healthy
        env_file:
            - .env
        networks:
            - dms-network
        ports:
            - "8000:8000" # webserver 
            - "8888:8888" # jupyter notebook
        user: ${USER_PYTHON}
        volumes:
            # - ./conf/l:/usr/local/bin/l
            # - ./${INBOX}:${OUTBOX}
            - ./dms-backend:${DIR_PYTHON}
            - media_volume:${DIR_PYTHON}/media
            - static_volume:${DIR_PYTHON}/staticfiles

    # =================NGINX=SERVICE=======================
    platform-nginx:
        container_name: nginx
        depends_on:
            dms-backend:
                condition: service_started
        env_file:
            - .env
        image: nginx:alpine
        networks:
            - dms-network
        ports:
            - "80:80"
        restart: always
        # volumes:
        # - ./conf/l:/usr/local/bin/l
        # - ./conf/default.conf:/etc/nginx/conf.d/default.conf
        # - media_volume:${DIR_NGINX}/media
        # - static_volume:${DIR_NGINX}/staticfiles

        # =========NETWORKS===========
networks:
    dms-network:
        driver: bridge

# =========VOLUMES============
volumes:
    static_volume: null
    media_volume: null
    postgis-data: null
